# Generated by Django 3.1.4 on 2020-12-23 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('battle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_health', models.IntegerField()),
                ('curr_health', models.IntegerField()),
                ('enemy_type', models.CharField(choices=[('rat', 'rat'), ('slime', 'slime')], max_length=7)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.battle')),
            ],
        ),
    ]
