# Generated by Django 3.1.4 on 2020-12-23 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enemy', '0002_auto_20201223_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemy',
            name='enemy_name',
            field=models.CharField(choices=[('rat', 'Rat'), ('slime', 'Slime')], max_length=7),
        ),
    ]
