# Generated by Django 3.1.4 on 2020-12-23 01:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enemy', '0003_auto_20201223_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='field_position',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
