# Generated by Django 3.1.4 on 2020-12-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enemy', '0004_enemy_field_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='block',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
