# Generated by Django 3.1.4 on 2020-12-26 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enemy', '0005_enemy_block'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enemy',
            old_name='enemy_name',
            new_name='name',
        ),
    ]
