# Generated by Django 3.1.4 on 2020-12-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enemy', '0006_auto_20201226_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='status_effects',
            field=models.JSONField(default=list),
        ),
    ]
