# Generated by Django 3.1.4 on 2020-12-23 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.IntegerField(default=1)),
                ('curr_health', models.IntegerField()),
                ('max_health', models.IntegerField()),
                ('curr_mana', models.IntegerField()),
                ('max_mana', models.IntegerField()),
                ('hand', models.JSONField(default=list)),
                ('discard', models.JSONField(default=list)),
                ('deck', models.JSONField(default=list)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
        ),
    ]
