# Generated by Django 3.1.4 on 2020-12-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='curr_mana',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='battle',
            name='max_mana',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
