# Generated by Django 3.1.4 on 2020-12-26 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0002_battle_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='buffs',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='battle',
            name='debuffs',
            field=models.JSONField(default=list),
        ),
    ]
