# Generated by Django 3.1.4 on 2020-12-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0004_auto_20201226_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='status_effects',
            field=models.JSONField(default=list),
        ),
    ]
