# Generated by Django 3.1.4 on 2020-12-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0006_auto_20201228_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='relics',
            field=models.JSONField(default=dict),
        ),
    ]
