# Generated by Django 3.1.4 on 2020-12-23 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamestate', models.CharField(choices=[('battle', 'battle'), ('shop', 'shop'), ('event', 'event'), ('map', 'map'), ('rewards', 'rewards')], max_length=7)),
                ('curr_health', models.IntegerField()),
                ('max_health', models.IntegerField()),
                ('max_mana', models.IntegerField()),
                ('gold', models.IntegerField()),
                ('deck', models.JSONField(default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
