# Generated by Django 3.1.4 on 2020-12-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='relic',
            field=models.JSONField(default=dict),
        ),
    ]
