# Generated by Django 3.1.4 on 2020-12-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_max_mana'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='deck',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
