# Generated by Django 3.1.4 on 2020-12-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_deck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='deck',
            field=models.JSONField(default=dict),
        ),
    ]
